# encoding:utf-8
from sqlalchemy import Column, Index, Integer, MetaData, Table, Text

metadata = MetaData()

investment_users = Table(
    "customers",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("openid", Text, nullable=False),
    Column("name", Text),
    Column("institution", Text),
    Column("mobile", Text),
    Column("enabled", Integer, nullable=False, server_default="1"),
    Column("allowed_services", Text, nullable=False),
    Column("auth_start_at", Text),
    Column("auth_end_at", Text),
    Column("remark", Text),
    Column("created_by_admin_id", Integer),
    Column("created_by_username", Text),
    Column("updated_by_admin_id", Integer),
    Column("updated_by_username", Text),
    Column("deleted_at", Text),
    Column("deleted_by_admin_id", Integer),
    Column("deleted_by_username", Text),
    Column("delete_reason", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("idx_customers_openid", "openid", unique=True),
)

investment_admin_users = Table(
    "admins",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("username", Text, nullable=False),
    Column("password_hash", Text, nullable=False),
    Column("role", Text, nullable=False),
    Column("enabled", Integer, nullable=False, server_default="1"),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("last_login_at", Text),
    Index("idx_admins_username", "username", unique=True),
)

investment_admin_sessions = Table(
    "admin_sessions",
    metadata,
    Column("session_id", Text, primary_key=True),
    Column("user_id", Integer, nullable=False),
    Column("token_hash", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("expires_at", Text, nullable=False),
    Index("idx_admin_sessions_token", "token_hash", unique=True),
    Index("idx_admin_sessions_user", "user_id"),
)

investment_request_records = Table(
    "request_records",
    metadata,
    Column("request_id", Text, primary_key=True),
    Column("openid", Text, nullable=False),
    Column("raw_input", Text, nullable=False),
    Column("service", Text, key="service_type"),
    Column("entry_type", Text),
    Column("action_type", Text),
    Column("actor_type", Text),
    Column("actor_id", Text),
    Column("actor_name", Text),
    Column("actor_role", Text),
    Column("status", Text, nullable=False),
    Column("error_code", Text),
    Column("user_prompt", Text),
    Column("error", Text, key="error_message"),
    Column("outputs", Text, key="output_files"),
    Column("normalized_target", Text),
    Column("stock_code", Text),
    Column("stock_name", Text),
    Column("customer_name", Text),
    Column("institution", Text),
    Column("market_date", Text),
    Column("cache_key", Text),
    Column("cache_hit", Integer),
    Column("program_version", Text),
    Column("ta_version", Text),
    Column("renderer_version", Text),
    Column("template_version", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("elapsed_ms", Integer),
    Index("idx_request_records_created", "created_at"),
    Index("idx_request_records_service_status", "service_type", "status"),
    Index("idx_request_records_entry_created", "entry_type", "created_at"),
)

investment_daily_contents = Table(
    "content_records",
    metadata,
    Column("content_id", Text, primary_key=True),
    Column("service", Text, nullable=False, key="service_type"),
    Column("sources", Text, key="source_files"),
    Column("input_text", Text, key="source_text"),
    Column("output_text", Text, key="generated_text"),
    Column("output_image_path", Text, key="output_image"),
    Column("status", Text, nullable=False),
    Column("error", Text, key="error_message"),
    Column("operator", Text),
    Column("created_by_admin_id", Integer),
    Column("created_by_username", Text),
    Column("created_by_role", Text),
    Column("updated_by_admin_id", Integer),
    Column("updated_by_username", Text),
    Column("updated_by_role", Text),
    Column("published_by_admin_id", Integer),
    Column("published_by_username", Text),
    Column("published_by_role", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("effective_at", Text),
    Column("effective_date", Text),
    Column("expires_at", Text),
    Column("content_version", Integer, nullable=False, server_default="1"),
    Column("direct_output_mode", Integer, nullable=False, server_default="0"),
    Column("auto_effective_after_generate", Integer, nullable=False, server_default="0"),
    Column("archived_at", Text),
    Index("idx_content_records_service_status", "service_type", "status"),
    Index("idx_content_records_effective", "service_type", "effective_at"),
    Index("idx_content_records_effective_date", "service_type", "effective_date", "status"),
)

investment_output_files = Table(
    "artifacts",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("owner_id", Text),
    Column("owner_type", Text),
    Column("file_path", Text, nullable=False),
    Column("file_type", Text),
    Column("service", Text, key="service_type"),
    Column("artifact_role", Text),
    Column("file_size", Integer),
    Column("file_hash", Text),
    Column("version_tag", Text),
    Column("created_at", Text, nullable=False),
    Index("idx_artifacts_owner", "owner_id"),
)

investment_cache_entries = Table(
    "cache_entries",
    metadata,
    Column("cache_key", Text, primary_key=True),
    Column("service", Text, nullable=False, key="service_type"),
    Column("normalized_target", Text, nullable=False),
    Column("market_date", Text, nullable=False),
    Column("version_fingerprint", Text, nullable=False),
    Column("outputs", Text, nullable=False, key="output_files"),
    Column("artifact_owner_id", Text),
    Column("status", Text, nullable=False),
    Column("hit_count", Integer, nullable=False, server_default="0"),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("idx_cache_entries_lookup", "service_type", "normalized_target", "market_date", "version_fingerprint", "status"),
    Index("idx_cache_entries_service_date", "service_type", "market_date", "status"),
)

investment_configs = Table(
    "configs",
    metadata,
    Column("config_key", Text, primary_key=True),
    Column("config_value", Text),
    Column("updated_at", Text, nullable=False),
    Column("updated_by", Text),
    Column("updated_by_admin_id", Integer),
    Column("updated_by_username", Text),
    Column("updated_by_role", Text),
)

investment_operation_audits = Table(
    "operation_audits",
    metadata,
    Column("audit_id", Text, primary_key=True),
    Column("operator", Text),
    Column("operator_admin_id", Integer),
    Column("operator_username", Text),
    Column("operator_role", Text),
    Column("category", Text, key="operation_category"),
    Column("result", Text, key="result_status"),
    Column("error_code", Text),
    Column("error", Text, key="error_message"),
    Column("elapsed_ms", Integer),
    Column("before_state", Text),
    Column("after_state", Text),
    Column("action", Text, nullable=False),
    Column("target_type", Text, nullable=False),
    Column("target_id", Text),
    Column("detail", Text),
    Column("request_ip", Text),
    Column("user_agent", Text),
    Column("created_at", Text, nullable=False),
    Index("idx_operation_audits_created", "created_at"),
    Index("idx_operation_audits_target", "target_type", "target_id"),
)

investment_stock_symbols = Table(
    "stock_symbols",
    metadata,
    Column("code", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("market", Text, nullable=False),
    Column("ts_code", Text),
    Column("source", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("idx_stock_symbols_name", "name"),
    Index("idx_stock_symbols_updated", "updated_at"),
)

request_events = Table(
    "request_events",
    metadata,
    Column("event_id", Text, primary_key=True),
    Column("request_id", Text, nullable=False),
    Column("openid", Text, nullable=False),
    Column("channel", Text, nullable=False),
    Column("event_type", Text, nullable=False),
    Column("message_type", Text),
    Column("content", Text),
    Column("media_id", Text),
    Column("file_path", Text),
    Column("source_type", Text),
    Column("source_id", Text),
    Column("result", Text),
    Column("error", Text),
    Column("created_at", Text, nullable=False),
    Index("idx_request_events_request_created", "request_id", "created_at"),
    Index("idx_request_events_openid_created", "openid", "created_at"),
    Index("idx_request_events_type_created", "event_type", "created_at"),
)

internal_call_records = Table(
    "internal_call_records",
    metadata,
    Column("call_id", Text, primary_key=True),
    Column("entry_type", Text, nullable=False),
    Column("service", Text, nullable=False, key="service_type"),
    Column("action_type", Text, nullable=False),
    Column("actor_type", Text, nullable=False),
    Column("actor_id", Text),
    Column("actor_name", Text),
    Column("actor_role", Text),
    Column("input_text", Text),
    Column("sources", Text, nullable=False),
    Column("status", Text, nullable=False),
    Column("error_code", Text),
    Column("error", Text),
    Column("output_text", Text),
    Column("outputs", Text, nullable=False),
    Column("elapsed_ms", Integer),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("idx_internal_call_records_entry_created", "entry_type", "created_at"),
    Index("idx_internal_call_records_service_created", "service_type", "created_at"),
    Index("idx_internal_call_records_actor_created", "actor_name", "created_at"),
)

ai_generation_audits = Table(
    "ai_generation_audits",
    metadata,
    Column("audit_id", Text, primary_key=True),
    Column("entry_type", Text, nullable=False),
    Column("service", Text, nullable=False, key="service_type"),
    Column("action_type", Text, nullable=False),
    Column("actor_type", Text, nullable=False),
    Column("actor_id", Text),
    Column("actor_name", Text),
    Column("actor_role", Text),
    Column("business_record_type", Text),
    Column("business_record_id", Text),
    Column("input_text", Text),
    Column("sources", Text, nullable=False),
    Column("provider", Text),
    Column("model", Text),
    Column("result", Text, nullable=False),
    Column("error_code", Text),
    Column("error", Text),
    Column("output_text", Text),
    Column("outputs", Text, nullable=False),
    Column("elapsed_ms", Integer),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("idx_ai_generation_audits_business", "business_record_type", "business_record_id"),
    Index("idx_ai_generation_audits_service_created", "service_type", "created_at"),
    Index("idx_ai_generation_audits_actor_created", "actor_name", "created_at"),
)

# New concise table aliases. Keep the legacy Python names above so existing
# service modules can continue importing them while the physical table names
# are simplified.
customers = investment_users
admins = investment_admin_users
admin_sessions = investment_admin_sessions
request_records = investment_request_records
content_records = investment_daily_contents
artifacts = investment_output_files
cache_entries = investment_cache_entries
configs = investment_configs
operation_audits = investment_operation_audits
stock_symbols = investment_stock_symbols
internal_calls = internal_call_records
ai_audits = ai_generation_audits
