# encoding:utf-8
from sqlalchemy import Column, Index, Integer, MetaData, Table, Text

metadata = MetaData()

investment_users = Table(
    "investment_users",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("openid", Text, nullable=False),
    Column("name", Text),
    Column("institution", Text),
    Column("mobile", Text),
    Column("enabled", Integer, nullable=False, server_default="1"),
    Column("allowed_services", Text, nullable=False),
    Column("auth_start_at", Text),
    Column("auth_end_at", Text),
    Column("remark", Text),
    Column("created_by_admin_id", Integer),
    Column("created_by_username", Text),
    Column("updated_by_admin_id", Integer),
    Column("updated_by_username", Text),
    Column("deleted_at", Text),
    Column("deleted_by_admin_id", Integer),
    Column("deleted_by_username", Text),
    Column("delete_reason", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("idx_investment_users_openid", "openid", unique=True),
)

investment_admin_users = Table(
    "investment_admin_users",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("username", Text, nullable=False),
    Column("password_hash", Text, nullable=False),
    Column("role", Text, nullable=False),
    Column("enabled", Integer, nullable=False, server_default="1"),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("last_login_at", Text),
    Index("idx_investment_admin_users_username", "username", unique=True),
)

investment_admin_sessions = Table(
    "investment_admin_sessions",
    metadata,
    Column("session_id", Text, primary_key=True),
    Column("user_id", Integer, nullable=False),
    Column("token_hash", Text, nullable=False),
    Column("created_at", Text, nullable=False),
    Column("expires_at", Text, nullable=False),
    Index("idx_investment_admin_sessions_token", "token_hash", unique=True),
    Index("idx_investment_admin_sessions_user", "user_id"),
)

investment_request_records = Table(
    "investment_request_records",
    metadata,
    Column("request_id", Text, primary_key=True),
    Column("openid", Text, nullable=False),
    Column("raw_input", Text, nullable=False),
    Column("service_type", Text),
    Column("status", Text, nullable=False),
    Column("error_code", Text),
    Column("user_prompt", Text),
    Column("error_message", Text),
    Column("output_files", Text),
    Column("normalized_target", Text),
    Column("stock_code", Text),
    Column("stock_name", Text),
    Column("customer_name", Text),
    Column("institution", Text),
    Column("market_date", Text),
    Column("cache_key", Text),
    Column("cache_hit", Integer),
    Column("program_version", Text),
    Column("ta_version", Text),
    Column("renderer_version", Text),
    Column("template_version", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("elapsed_ms", Integer),
    Index("idx_investment_request_records_created", "created_at"),
    Index("idx_investment_request_records_service_status", "service_type", "status"),
)

investment_daily_contents = Table(
    "investment_daily_contents",
    metadata,
    Column("content_id", Text, primary_key=True),
    Column("service_type", Text, nullable=False),
    Column("source_files", Text),
    Column("source_text", Text),
    Column("generated_text", Text),
    Column("output_image", Text),
    Column("status", Text, nullable=False),
    Column("error_message", Text),
    Column("operator", Text),
    Column("created_by_admin_id", Integer),
    Column("created_by_username", Text),
    Column("created_by_role", Text),
    Column("updated_by_admin_id", Integer),
    Column("updated_by_username", Text),
    Column("updated_by_role", Text),
    Column("published_by_admin_id", Integer),
    Column("published_by_username", Text),
    Column("published_by_role", Text),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Column("effective_at", Text),
    Column("effective_date", Text),
    Column("content_version", Integer, nullable=False, server_default="1"),
    Column("direct_output_mode", Integer, nullable=False, server_default="0"),
    Column("archived_at", Text),
    Index("idx_investment_daily_contents_service_status", "service_type", "status"),
    Index("idx_investment_daily_contents_effective", "service_type", "effective_at"),
    Index("idx_investment_daily_contents_effective_date", "service_type", "effective_date", "status"),
)

investment_output_files = Table(
    "investment_output_files",
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("owner_id", Text),
    Column("owner_type", Text),
    Column("file_path", Text, nullable=False),
    Column("file_type", Text),
    Column("service_type", Text),
    Column("artifact_role", Text),
    Column("file_size", Integer),
    Column("file_hash", Text),
    Column("version_tag", Text),
    Column("created_at", Text, nullable=False),
    Index("idx_investment_output_files_owner", "owner_id"),
)

investment_cache_entries = Table(
    "investment_cache_entries",
    metadata,
    Column("cache_key", Text, primary_key=True),
    Column("service_type", Text, nullable=False),
    Column("normalized_target", Text, nullable=False),
    Column("market_date", Text, nullable=False),
    Column("version_fingerprint", Text, nullable=False),
    Column("output_files", Text, nullable=False),
    Column("artifact_owner_id", Text),
    Column("status", Text, nullable=False),
    Column("hit_count", Integer, nullable=False, server_default="0"),
    Column("created_at", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("idx_investment_cache_lookup", "service_type", "normalized_target", "market_date", "version_fingerprint", "status"),
    Index("idx_investment_cache_service_date", "service_type", "market_date", "status"),
)

investment_configs = Table(
    "investment_configs",
    metadata,
    Column("config_key", Text, primary_key=True),
    Column("config_value", Text),
    Column("updated_at", Text, nullable=False),
    Column("updated_by", Text),
    Column("updated_by_admin_id", Integer),
    Column("updated_by_username", Text),
    Column("updated_by_role", Text),
)

investment_operation_audits = Table(
    "investment_operation_audits",
    metadata,
    Column("audit_id", Text, primary_key=True),
    Column("operator", Text),
    Column("operator_admin_id", Integer),
    Column("operator_username", Text),
    Column("operator_role", Text),
    Column("operation_category", Text),
    Column("result_status", Text),
    Column("error_code", Text),
    Column("error_message", Text),
    Column("elapsed_ms", Integer),
    Column("before_state", Text),
    Column("after_state", Text),
    Column("action", Text, nullable=False),
    Column("target_type", Text, nullable=False),
    Column("target_id", Text),
    Column("detail", Text),
    Column("request_ip", Text),
    Column("user_agent", Text),
    Column("created_at", Text, nullable=False),
    Index("idx_investment_operation_audits_created", "created_at"),
    Index("idx_investment_operation_audits_target", "target_type", "target_id"),
)

investment_stock_symbols = Table(
    "investment_stock_symbols",
    metadata,
    Column("code", Text, primary_key=True),
    Column("name", Text, nullable=False),
    Column("market", Text, nullable=False),
    Column("ts_code", Text),
    Column("source", Text, nullable=False),
    Column("updated_at", Text, nullable=False),
    Index("idx_investment_stock_symbols_name", "name"),
    Index("idx_investment_stock_symbols_updated", "updated_at"),
)
